---
- name: Test for docker command
  shell: which docker
  register: docker
  failed_when: false

  # Install Docker Engine if does not exist already
- name: Add docker key
  apt_key: keyserver={{ keyserver }} id={{ docker_key }}
  when: docker.rc >= 1

- name: Add docker repo config
  copy: content={{ docker_repo_cfg }} dest={{ docker_repo_path }}
  when: docker.rc >= 1

- name: Purge lxc-docker
  apt: name=lxc-docker state=absent
  when: docker.rc >= 1

- name: Install docker-engine
  apt: name={{ item }} update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ ansible_kernel }}
    - apparmor
    - docker-engine
  when: docker.rc >= 1

- name: Adding user {{ user }} to docker group
  user: name={{ user }}
        groups=docker
        append=yes
  when: docker.rc >= 1
