---
# tasks file for oracle-java

# Install Software Properties Commmon Package for Easy PPA config
- name: Install add-apt-repostory
  become: true
  apt: name=software-properties-common state=latest

# Add Oracle's Personal Package Archive repo
- name: Add Oracle Java Repository
  become: true
  apt_repository: repo='ppa:webupd8team/java'

# Use DebConf to Accept Oracle's License
- name: Accept Java 8 License
  become: true
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

# With Repository Added, Install Oracle Java8 installer and install it
- name: Install Oracle Java 8
  become: true
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
