---
# defaults file for testpoodle
docker_repo_path: /etc/apt/sources.list.d/docker.list
docker_repo_cfg: deb https://apt.dockerproject.org/repo ubuntu-trusty main
keyserver: p80.pool.sks-keyservers.net
docker_key: 58118E89F3A912897C070ADBF76221572C52609D
