galaxy_info:
  author: Joaquin Menchaca
  description: Installs Neo4j graph database
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
dependencies:
  - oracle-java
