---
galaxy_info:
  author: Joaquin Menchaca
  description: Installs Oracle Java 8
  company: Joaqiun Menchaca
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  galaxy_tags:
  - development
  - system
  - web
dependencies: []
